### ISSUE TITLE
Analysis code fixes

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/interactive-templates#105]
This is a list of small changes for the analysis code

- [x] Recode IMD to [Most deprived, 2, 3, 4, Least deprived]. Drop missing imd (0) from the charts. #129
- [x] The population rate chart is missing the dark grid styling of the other charts. #130
- [x] The x ticks (dates) are too close together. We could plot every other month. #130
- [x] Change x ticks from e.g. 2020-01-01 to Jan 2021. #130
- [x] Comma delimit large counts in event table (this is now handled on jobserver)
- [x] Update the ordering of the legend for the age band plots. These should always be in age order #130
- [x] When outer percentiles are shown, they are not represented in the legend #130 
- [x] In the events counts tables, show redacted counts as `[REDACTED]` #130
